### PR TITLE
Do not modify nested input search criteria

### LINKED ISSUE #10: Criteria building modifies input dict
```python
>>> criteria = [{"link": "AND", "criteria": [{"field": "Computer.name", "searchtype": "contains", "value": "example.com"}]}]
>>> glpi.search("Computer", criteria=criteria)
# returns the expected result
>>> print(criteria)
[{"link": "AND"}]
```
This is a problem when the input criteria are supposed to be used for another invocation, like when you have children groups in an Ansible GLPI inventory.

I'll open a PR fixing this in a minute.

### PR DESCRIPTION
**Pull request by jplitza**
Fixes #10

### CODE REVIEW

**Comment by jplitza** [comment]
Whoops, the original commit also added the original dict to the request. The `pop()` actually had a reason! ;-)

So I added an exception in the loop that adds all other parameters. The alternative would be to operate on deep clones, but that doesn't seem necessary.

**Comment by fmenabe** [comment]
Thanks for the PR!

I release a new version on Pypi (_0.3.3_).

**Comment by jplitza** [comment]
Thanks for merging!

However, your PyPi release somehow got screwed up. The git tag contains my changes, but the PyPi release doesn't!

**Comment by fmenabe** [comment]
Sorry, I messed up the generation of the package before uploading it. 

A new version (0.3.4) has been released!

**Pull request merged**
