### PR TITLE
Remove 'itemtype' from 'uid' only at the beginning

### LINKED ISSUE #14: _map_fields removes the itemtype from the fields uid incorrectly
Method `_map_fields` replaces the fields `uid` to remove  the `itemtype` from it.

I've one field with uid `Ticket.Group_Ticket.Group.completename` that gets translated to `Group_Group.completename`, but should be `Group_Ticket.Group.completename`

The `itemtype` should be deleted only from the beginning of the `uid`

### PR DESCRIPTION
**Pull request by pniaps**
Fixes #14

### CODE REVIEW

**Comment by fmenabe** [comment]
Thanks for the PR!

**Comment by fmenabe** [comment]
I've also release a new version (*0.3.5*) on Pypi.

**Comment by pniaps** [comment]
Thanks

**Comment by pniaps** [comment]
This is a breaking change if someone is using _the old replaced_ Keys.

**Pull request merged**
